FROM node:22.20.0-alpine

ENV NODE_ENV=production
WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
RUN npm ci --omit=dev && npm cache clean --force
COPY src ./src

USER node
EXPOSE 8080

CMD ["node", "src/server.js"]
